# Generated by Django 3.2.19 on 2023-07-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('colBandera', models.CharField(max_length=100)),
                ('fundacion', models.DateField()),
                ('diaNacional', models.DateField()),
                ('baileNacional', models.CharField(max_length=100)),
                ('animalNacional', models.CharField(max_length=100)),
            ],
        ),
    ]
